version: "3.8"
services:
  postgresdb:
    image: postgres:16.4
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgresdb
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8080:80
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
